/* ============================================================
   TERMS OF SERVICE PAGE
   ============================================================
   Standard terms covering acceptable use, payment terms,
   limitations of liability, and service guarantees.
   ============================================================ */

export const metadata = {
  title: "Terms of Service — JobPilot AI",
};

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-16 sm:py-24">
      <h1 className="font-[family-name:var(--font-space-grotesk)] text-4xl sm:text-5xl font-bold mb-4 glow-text-strong">
        Terms of Service
      </h1>
      <p className="text-text-muted mb-12">Last updated: May 4, 2026</p>

      <div className="space-y-10 text-text-secondary leading-relaxed">
        {/* Section 1 */}
        <section>
          <h2 className="text-xl font-bold text-white mb-4">1. Acceptance of Terms</h2>
          <p>
            By accessing or using JobPilot AI, you agree to be bound by these Terms of Service.
            If you do not agree to these terms, please do not use our service.
            These terms apply to all visitors, users, and paying subscribers.
          </p>
        </section>

        {/* Section 2 */}
        <section>
          <h2 className="text-xl font-bold text-white mb-4">2. Description of Service</h2>
          <p>
            JobPilot AI provides AI-powered career tools including resume analysis and optimization,
            cover letter generation, interview preparation, job matching, and application tracking.
            Our AI features are powered by Google Gemini and the quality of outputs may vary.
          </p>
        </section>

        {/* Section 3 */}
        <section>
          <h2 className="text-xl font-bold text-white mb-4">3. User Accounts</h2>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li>You must provide accurate and complete information when creating an account.</li>
            <li>You are responsible for maintaining the security of your password.</li>
            <li>You must be at least 16 years old to use this service.</li>
            <li>One account per person. Shared accounts are not permitted.</li>
          </ul>
        </section>

        {/* Section 4 */}
        <section>
          <h2 className="text-xl font-bold text-white mb-4">4. Subscription & Payments</h2>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li>Free accounts include limited AI usage (3 calls per month).</li>
            <li>Pro and Enterprise plans are billed monthly via Stripe.</li>
            <li>You may cancel your subscription at any time. Access continues until the end of the billing period.</li>
            <li>Refunds are available within 7 days of purchase if you have not used the AI features.</li>
            <li>Prices may change with 30 days notice to existing subscribers.</li>
          </ul>
        </section>

        {/* Section 5 */}
        <section>
          <h2 className="text-xl font-bold text-white mb-4">5. Acceptable Use</h2>
          <p className="mb-3">You agree not to:</p>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li>Use the service to generate fraudulent, misleading, or dishonest resume content.</li>
            <li>Attempt to bypass usage limits or access controls.</li>
            <li>Use automated tools to scrape or bulk-access the service.</li>
            <li>Upload content that violates any laws or contains malware.</li>
            <li>Resell or redistribute AI-generated content as a competing service.</li>
          </ul>
        </section>

        {/* Section 6 */}
        <section>
          <h2 className="text-xl font-bold text-white mb-4">6. AI-Generated Content</h2>
          <p>
            Content generated by our AI tools (resumes, cover letters, interview answers) is provided
            as suggestions. You are responsible for reviewing, editing, and verifying all AI-generated
            content before using it. We do not guarantee that AI-generated content will result in
            job interviews or offers. Always fact-check AI outputs against your actual experience.
          </p>
        </section>

        {/* Section 7 */}
        <section>
          <h2 className="text-xl font-bold text-white mb-4">7. Limitation of Liability</h2>
          <p>
            JobPilot AI is provided &ldquo;as is&rdquo; without warranties of any kind. We are not
            liable for any damages arising from the use of our service, including but not limited to
            lost job opportunities, inaccurate AI outputs, or service interruptions. Our total
            liability is limited to the amount you paid us in the 12 months preceding the claim.
          </p>
        </section>

        {/* Section 8 */}
        <section>
          <h2 className="text-xl font-bold text-white mb-4">8. Changes to Terms</h2>
          <p>
            We may update these terms from time to time. We will notify registered users of
            significant changes via email. Continued use of the service after changes constitutes
            acceptance of the new terms.
          </p>
        </section>

        {/* Section 9 */}
        <section>
          <h2 className="text-xl font-bold text-white mb-4">9. Contact</h2>
          <p>
            For questions about these terms, contact us at{" "}
            <a href="mailto:support@jobpilotai.com" className="text-brand-light hover:text-white transition-colors">
              support@jobpilotai.com
            </a>.
          </p>
        </section>
      </div>
    </div>
  );
}
