/* ============================================================
   ROOT LAYOUT - JP Arc
   ============================================================
   This is the top-level layout that wraps every page.
   It sets up fonts, metadata (SEO), and the HTML shell.
   In Next.js App Router, layout.tsx is the equivalent of
   _document + _app from the Pages Router.
   ============================================================ */

import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Grotesk } from "next/font/google";
import { headers } from "next/headers";
import dynamic from "next/dynamic";
import { SoftwareAppJsonLd, OrganizationJsonLd, WebSiteJsonLd } from "@/components/JsonLd";
import "./globals.css";

/* Lazy-load the cookie consent banner — only renders on first visit */
const CookieConsent = dynamic(() => import("@/components/CookieConsent"));

/* ---- Font Setup ---- */
/* Geist is a clean, modern sans-serif font by Vercel — used for body text */
/* We load it as a CSS variable so Tailwind can reference it */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* Space Grotesk — geometric, premium display font for the brand name */
/* Used specifically for "JP Arc" headings and hero text */
/* Its sharp, techy letterforms fit the space theme perfectly */
const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

/* ---- SEO Metadata ---- */
/* This populates the <title> and <meta> tags in the HTML <head> */
/* Search engines and social media use these when displaying links */
export const metadata: Metadata = {
  title: {
    default: "Free AI Resume Builder, CV Templates & Mock Interviews — JP Arc",
    template: "%s — JP Arc",
  },
  description:
    "Build your resume in minutes, score it against ATS, and practice mock interviews — all free. 20+ CV templates, AI cover letters, and interview coaching used by 10,000+ job seekers.",
  keywords: [
    "free resume builder",
    "AI resume builder",
    "resume builder online free",
    "CV builder",
    "CV templates free",
    "ATS resume checker",
    "ATS resume builder",
    "resume templates",
    "professional resume template",
    "mock interview",
    "AI mock interview",
    "interview practice",
    "mock interview online",
    "cover letter generator",
    "AI cover letter",
    "resume optimizer",
    "resume score checker",
    "job application tracker",
    "career tools",
    "JP Arc",
  ],
  metadataBase: new URL("https://jobpilotai.co"),
  manifest: "/manifest.json",
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "48x48" },
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
    ],
    apple: [{ url: "/apple-icon.png", sizes: "180x180", type: "image/png" }],
  },
  openGraph: {
    type: "website",
    locale: "en_GB",
    url: "https://jobpilotai.co",
    siteName: "JP Arc",
    title: "Free AI Resume Builder, CV Templates & Mock Interviews — JP Arc",
    description:
      "Build your resume in minutes, score it against ATS, and practice mock interviews — all free. 20+ templates, AI cover letters, and interview coaching.",
    images: [{ url: "/og-image.png", width: 1200, height: 630, alt: "JP Arc — Free AI Resume Builder & Career Tools" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Free AI Resume Builder & Mock Interviews — JP Arc",
    description:
      "Build ATS-optimized resumes, practice mock interviews, generate cover letters — all free. Join 10,000+ job seekers landing interviews faster.",
    images: ["/og-image.png"],
  },
  alternates: {
    canonical: "https://jobpilotai.co",
  },
  other: {
    "trustpilot-one-time-domain-verification-id": "5a54acc0-7d23-406d-a570-f6983e589680",
  },
};

/* ---- Root Layout Component ---- */
/* Every page in the app is rendered inside this layout */
/* The {children} prop is whatever page component Next.js routes to */
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  /* Read CSP nonce generated by the proxy for inline script/style whitelisting */
  const nonce = (await headers()).get("x-nonce") ?? undefined;

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${spaceGrotesk.variable} antialiased`}
      style={{ colorScheme: "dark", backgroundColor: "#09090b" }}
    >
      <body className="min-h-screen flex flex-col" style={{ backgroundColor: "#09090b" }} nonce={nonce}>
        <SoftwareAppJsonLd />
        <OrganizationJsonLd />
        <WebSiteJsonLd />
        {children}
        <CookieConsent />
      </body>
    </html>
  );
}
